# Generated by Django 6.0.1 on 2026-06-27 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_role_employeerole'),
        ('warehouses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeprofile',
            name='accessible_departments',
            field=models.ManyToManyField(blank=True, help_text='Tick the departments this employee is allowed to manage/view.', related_name='accessed_by_employees', to='users.department'),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='accessible_warehouses',
            field=models.ManyToManyField(blank=True, help_text='Tick the warehouses this employee is allowed to operate in.', related_name='accessed_by_employees', to='warehouses.warehouse'),
        ),
    ]
