# Generated by Django 5.2.17 on 2026-08-23 19:58

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hr', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150)),
                ('product', models.CharField(max_length=255)),
                ('capacity', models.CharField(help_text="Free-form, e.g. '42 tons/day'.", max_length=50)),
                ('efficiency', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('processing', 'Processing')], default='active', max_length=12)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='QualityCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('result', models.CharField(choices=[('passed', 'Passed'), ('failed', 'Failed'), ('review', 'Needs review')], default='review', max_length=10)),
                ('notes', models.TextField(blank=True)),
                ('inspector', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quality_checks', to='hr.employee')),
                ('line', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quality_checks', to='production.productionline')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
