# Generated by Django 5.2.17 on 2026-08-23 19:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('full_name', models.CharField(max_length=255)),
                ('position', models.CharField(max_length=100)),
                ('department', models.CharField(choices=[('management', 'Management'), ('hr', 'Human Resources'), ('production', 'Production'), ('purchasing', 'Purchasing'), ('inventory', 'Inventory'), ('sales', 'Sales'), ('finance', 'Finance')], max_length=20)),
                ('hire_date', models.DateField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=10)),
                ('user', models.OneToOneField(blank=True, help_text='Linked only if this employee also has a system login.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='Payroll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('period', models.DateField(help_text='First day of the pay period month.')),
                ('base_salary', models.DecimalField(decimal_places=0, max_digits=14)),
                ('insurance_deduction', models.DecimalField(decimal_places=0, default=0, max_digits=14)),
                ('tax_deduction', models.DecimalField(decimal_places=0, default=0, max_digits=14)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed')], default='pending', max_length=12)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payroll_records', to='hr.employee')),
            ],
            options={
                'ordering': ['-period'],
                'constraints': [models.UniqueConstraint(fields=('employee', 'period'), name='unique_payroll_per_period')],
            },
        ),
    ]
