# Generated by Django 6.0.1 on 2026-06-23 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_stockmovement'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='minimum_quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
